### ISSUE TITLE
Развернуть образ Postgresql

### ISSUE THREAD

**Issue by AKKorotkov** [killarjan/User-Management-System#10]
Развернуть в докере образ PostgreSql
docker for windows должен быть запущен
1. Копируем прилуженный файл в папку projects/docker [docker-compose.zip](https://github.com/killarjan/User-Management-System/files/10068238/docker-compose.zip)
2. в папке, где распаковал архив и лежит файл docker-compose.yml в эксплорере запускаешь прям в строке, где путь к файлу cmd
откроется командная строка с корнем в текущей папке
3. выполняешь воманду в командной строке docker-compose up
4. начнет выкачиваться и разворачиваться образ, когда он завершит установку начнут печататься логи
5. Пробуешь подключиться к развернутому серверу
5.1. Открываешь  DBeaver
5.2. Database->New Database connection
5.3. Выбираешь PostgreSQL предложит установить драйвер, ставим
5.4. параметры задаем
Host = localhost
Port = 5432
Username = postgres
Password = mysecretpassword
На вкладке PostgreSQL проставить галочку Show all databases
Если все правильно, то при нажатии на кнопку  Test connection будет удачное подключение
Сохраняем настроенное подключение

**Comment by killarjan** [comment]
образ Postgresql развернут
![image](https://user-images.githubusercontent.com/70253855/203593011-75f3ddd4-188f-418d-aaf5-5ff8142a203d.png)
База данный подключена
![image](https://user-images.githubusercontent.com/70253855/203594451-1d0f782d-b642-49e4-ac07-f604d2593187.png)
