### ISSUE TITLE
Код запуска мигратора

### ISSUE THREAD

**Issue by AKKorotkov** [killarjan/User-Management-System#11]
В файл https://github.com/killarjan/User-Management-System/blob/develop/src/UserManagementSystem.Migrator/Program.cs добавляем код, который позволит запускать мигратор
`class Program
    {
        static void Main(string[] args)
        {
            RunMigrator.WithParameters(DbKind.Postges,
                "Host=localhost:5432;Database=UserManagementSystem;Username=postgres;Password=mysecretpassword", typeof(Program).Assembly, args);
        }
    }`

**Comment by killarjan** [comment]
При добавлении кода VS ругается что данные имена не в контексте
![image](https://user-images.githubusercontent.com/70253855/203597123-e8929166-db31-4d77-ba9d-65238d053f7d.png)
