### ISSUE TITLE
Добавляем БД

### ISSUE THREAD

**Issue by AKKorotkov** [killarjan/User-Management-System#12]
Подключиться к PostgreSQL в докере при помощи DVeaver
Создать базу данных UserManagementSystem
При создании БД в выпадающем списке  Owner выбрать postgres

**Comment by killarjan** [comment]
база данных UserManagementSystem создана
![image](https://user-images.githubusercontent.com/70253855/203596459-69d72f7a-fadd-42b6-ac9b-d3df55544d58.png)
